/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    AgentChat: typeof import('./src/components/agent-chat.vue')['default']
    AgentChat_bk: typeof import('./src/components/agent-chat_bk.vue')['default']
    AiRecommendStocksList: typeof import('./src/components/aiRecommendStocksList.vue')['default']
    AllStockInfoList: typeof import('./src/components/allStockInfoList.vue')['default']
    AllStockList: typeof import('./src/components/allStockList.vue')['default']
    AnalyzeMartket: typeof import('./src/components/AnalyzeMartket.vue')['default']
    ClsCalendarTimeLine: typeof import('./src/components/ClsCalendarTimeLine.vue')['default']
    CronTaskManager: typeof import('./src/components/cron-task-manager.vue')['default']
    EmbeddedUrl: typeof import('./src/components/EmbeddedUrl.vue')['default']
    FloatingAgentAssistant: typeof import('./src/components/FloatingAgentAssistant.vue')['default']
    FloatingAiAssistant: typeof import('./src/components/FloatingAiAssistant.vue')['default']
    Fund: typeof import('./src/components/fund.vue')['default']
    HotEvents: typeof import('./src/components/HotEvents.vue')['default']
    HotStockList: typeof import('./src/components/HotStockList.vue')['default']
    HotTopics: typeof import('./src/components/HotTopics.vue')['default']
    IndustryMoneyRank: typeof import('./src/components/industryMoneyRank.vue')['default']
    IndustryResearchReportList: typeof import('./src/components/IndustryResearchReportList.vue')['default']
    InvestCalendarTimeLine: typeof import('./src/components/InvestCalendarTimeLine.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart.vue')['default']
    LongTigerRankList: typeof import('./src/components/LongTigerRankList.vue')['default']
    Market: typeof import('./src/components/market.vue')['default']
    McpServerManager: typeof import('./src/components/mcp-server-manager.vue')['default']
    MoneyTrend: typeof import('./src/components/moneyTrend.vue')['default']
    NewsList: typeof import('./src/components/newsList.vue')['default']
    PromptPlaza: typeof import('./src/components/promptPlaza.vue')['default']
    PromptQa: typeof import('./src/components/promptQa.vue')['default']
    PromptTemplateList: typeof import('./src/components/promptTemplateList.vue')['default']
    RankTable: typeof import('./src/components/rankTable.vue')['default']
    ResearchIndex: typeof import('./src/components/researchIndex.vue')['default']
    ResearchReport: typeof import('./src/components/researchReport.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStock: typeof import('./src/components/SelectStock.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    SkillManager: typeof import('./src/components/skill-manager.vue')['default']
    Stock: typeof import('./src/components/stock.vue')['default']
    StockChangesMonitor: typeof import('./src/components/stockChangesMonitor.vue')['default']
    Stockhotmap: typeof import('./src/components/stockhotmap.vue')['default']
    StockLightweightKlineChart: typeof import('./src/components/StockLightweightKlineChart.vue')['default']
    StockNoticeList: typeof import('./src/components/StockNoticeList.vue')['default']
    StockResearchReportList: typeof import('./src/components/StockResearchReportList.vue')['default']
    StockSparkLine: typeof import('./src/components/stockSparkLine.vue')['default']
    TChat: typeof import('@tdesign-vue-next/chat')['Chat']
    TChatAction: typeof import('@tdesign-vue-next/chat')['ChatAction']
    TChatContent: typeof import('@tdesign-vue-next/chat')['ChatContent']
    TChatLoading: typeof import('@tdesign-vue-next/chat')['ChatLoading']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TradingRecordManager: typeof import('./src/components/TradingRecordManager.vue')['default']
    UplimitLadder: typeof import('./src/components/uplimitLadder.vue')['default']
  }
}
