export const indicatorTips = {
  ma: '趋势指标 | 用法：MA5/10看短期，MA20/60看中长线\n✅ 多头排列(5>10>20>60)持股，空头排列观望\n✅ 金叉买入，死叉卖出\n🔄 组合：MA+BOLL看支撑压力，MA+MACD确认趋势',
  boll: '波动率指标 | BOLL(20,2)\n✅ 收口=变盘前兆，开口=趋势启动\n✅ 触上轨超买，触下轨超卖(震荡市)\n✅ 中轨(20日均线)是多空分水岭\n🔄 组合：BOLL+Keltner=TTM Squeeze挤压策略',
  obv: '量价指标 | 能量潮\n✅ OBV上升+价涨=量价配合，趋势健康\n✅ OBV背离价格=趋势衰竭信号\n🔄 组合：OBV+MACD确认突破有效性',
  macd: '趋势+动量指标 | MACD(12,26,9)\n✅ 零轴上金叉=强势买入，零轴下死叉=弱势卖出\n✅ 顶背离(价新高MACD不新高)=见顶\n✅ 底背离(价新低MACD不新低)=见底\n🔄 组合：MACD+RSI双重确认，MACD+BOLL看转折',
  kdj: '震荡指标 | KDJ(9)\n✅ K上穿D金叉买入(20以下最准)\n✅ K下穿D死叉卖出(80以上最准)\n⚠️ 主升浪中KDJ长期超买别盲目卖\n🔄 组合：KDJ+RSI超买超卖共振，KDJ+BOLL触轨确认',
  rsi: '动量指标 | RSI(14)\n✅ RSI>70超买警惕回调，RSI<30超卖关注反弹\n✅ RSI>50多头占优，<50空头占优\n✅ 顶背离=诱多陷阱，坚决不追\n🔄 组合：RSI+MFI量价共振，RSI+MACD拐点确认',
  atr: '波动率指标 | ATR(14)\n✅ ATR大=波动剧烈，止损设宽\n✅ ATR小=波动平缓，止损设窄\n✅ 止损位=入场价±N×ATR(常用2倍)\n🔄 组合：ATR+Supertrend趋势跟踪，ATR+Keltner通道',
  vwap: '量价指标 | VWAP(20)\n✅ 价格在VWAP上方=多头主导\n✅ 价格在VWAP下方=空头主导\n✅ 机构常用VWAP做日内交易锚定价\n🔄 组合：VWAP+MFI确认资金方向',
  mfi: '量价指标 | MFI(14)\n✅ MFI>80超买，<20超卖\n✅ 量价版RSI，比RSI多考虑成交量\n✅ 背离时比RSI更早发出信号\n🔄 组合：MFI+RSI量价共振，MFI+VWAP主力资金追踪',
  kama: '自适应均线 | KAMA(10,2,30)\n✅ 趋势市自动变快，震荡市自动变慢\n✅ 解决MA在震荡市频繁假信号的问题\n✅ 价格突破KAMA=趋势启动信号\n🔄 组合：KAMA+ATR自适应止损',
  keltner: '波动率通道 | Keltner(20,10,1.5)\n✅ 价格突破上轨=强势，突破下轨=弱势\n✅ 与BOLL配合：BOLL收窄到Keltner内=挤压\n🔄 组合：Keltner+BOLL=TTM Squeeze挤压策略',
  supertrend: '趋势跟踪指标 | Supertrend(10,3)\n✅ 红线持股(看多)，绿线观望(看空)，最简洁的趋势信号\n✅ 可做移动止损：价格跌破红线止盈\n✅ A股短线波段神器，日线级别最准\n🔄 组合：Supertrend+EMA确认方向，Supertrend+ATR动态止损',
  ema: '趋势指标 | EMA(12,21)\n✅ EMA12上穿EMA21=金叉买入\n✅ EMA12下穿EMA21=死叉卖出\n✅ 比SMA更灵敏，短线操盘手偏爱\n🔄 组合：EMA+Supertrend趋势确认，EMA+MACD多级过滤',
  ichimoku: '综合指标 | 一目均衡表(9,26,52)\n🔴 转换(9) 蓝色基准(26) 绿虚先行A(26) 红虚先行B(52) 紫点迟行(26)\n✅ 价格在云层(先行A与先行B之间)上方=多头，下方=空头\n✅ 转换上穿基准=金叉买入，下穿=死叉卖出\n✅ 先行A在先行B上方=云层偏多(绿云)，反之偏空(红云)\n✅ 迟行在价格上方=长期看多，下方=长期看空\n🔄 组合：Ichimoku+MACD多重趋势确认',
  cci: '震荡+趋势指标 | CCI(20)\n✅ CCI>+100=强势追涨，<-100=弱势关注\n✅ CCI回穿±100=趋势确认信号\n✅ 比KDJ/RSI更灵活，不受0-100限制\n🔄 组合：CCI+MACD趋势启动，CCI+BOLL超买超卖',
  ttmSqueeze: '波动率+动量指标 | TTM Squeeze\n✅ 黄色圆点=波动挤压中(即将爆发)\n✅ 绿色圆点=挤压释放(趋势已启动)\n✅ 柱状图正值=多头动量，负值=空头动量\n✅ BOLL收窄到Keltner内=挤压，扩张=释放\n🔄 组合：TTM Squeeze+Supertrend突破确认',
  sar: '趋势跟踪指标 | Parabolic SAR(0.02,0.2)\n✅ 价格下方出现红点=多头持股\n✅ 价格上方出现绿点=空头观望\n✅ 点位即为移动止损位，跌破即走\n⚠️ 震荡市频繁翻转，配合ADX过滤\n🔄 组合：SAR+ADX趋势确认，SAR+Supertrend双重止损',
  donchian: '突破通道指标 | Donchian(20)\n✅ 价格突破上轨=创新高买入\n✅ 价格跌破下轨=创新低卖出\n✅ 海龟交易法核心指标\n✅ 中轨=(最高+最低)/2，可做均值回归\n🔄 组合：Donchian+ATR仓位管理，Donchian+SAR止损',
  adx: '趋势强度指标 | ADX(14)\n✅ ADX>25=趋势行情，顺势操作\n✅ ADX<20=震荡行情，不做趋势交易\n✅ ADX从下上穿25=趋势正在形成\n✅ +DI>-DI=多头力量，-DI>+DI=空头力量\n🔄 组合：ADX+MACD过滤假信号，ADX+Supertrend趋势确认',
  williamsR: '超买超卖指标 | Williams %R(14)\n✅ %R>-20超买，<-80超卖\n✅ 比KDJ更敏感，信号更早\n✅ 超买区拐头向下=卖出信号\n✅ 超卖区拐头向上=买入信号\n🔄 组合：WilliamsR+RSI超买超卖共振',
  stochRsi: '灵敏度增强指标 | StochRSI(14,14,3,3)\n✅ RSI的随机化，灵敏度远超普通RSI\n✅ 值>80超买，<20超卖\n✅ 适合短线1-3天拐点捕捉\n⚠️ 信号多但噪声也多，需配合趋势指标\n🔄 组合：StochRSI+MACD过滤假信号，StochRSI+BOLL辅助判断',
  cmf: '资金流向指标 | CMF(20)\n✅ CMF>0=资金流入，多头占优\n✅ CMF<0=资金流出，空头占优\n✅ CMF背离价格=主力资金异动\n✅ 比OBV更精确的量价分析\n🔄 组合：CMF+MFI资金确认，CMF+MACD趋势+资金共振',
  aroon: '趋势启停指标 | Aroon(25)\n✅ Aroon Up=100=刚创新高，Down=100=刚创新低\n✅ Up>70且Down<30=上升趋势启动\n✅ Down>70且Up<30=下降趋势启动\n✅ 两线交叉=趋势方向切换信号\n🔄 组合：Aroon+ADX确认趋势形成，Aroon+Supertrend趋势跟踪',
  cmo: '纯动量指标 | CMO(14)\n✅ CMO>0=多头动量，<0=空头动量\n✅ |CMO|>50=极端动量，可能反转\n✅ 去除价格绝对值影响，只看动量变化\n✅ 比RSI更纯粹的动量衡量\n🔄 组合：CMO+MACD动量确认，CMO+ADX趋势+动量',
  forceIndex: '量价动量指标 | Force Index(13)\n✅ FI>0=多头力量占优，<0=空头力量\n✅ FI创高新=多头力量增强\n✅ FI与价格背离=趋势衰竭\n✅ Elder三重过滤法核心指标\n🔄 组合：ForceIndex+EMA趋势过滤，ForceIndex+MACD背离确认',
  pivot: '支撑阻力指标 | Pivot Points\n✅ PP=前日(H+L+C)/3，多空分水岭\n✅ R1/R2=阻力位，触及易回落\n✅ S1/S2=支撑位，触及易反弹\n✅ 日内交易者开盘必看\n🔄 组合：Pivot+BOLL双重支撑阻力，Pivot+VWAP日内锚定',
  dema: '快速均线指标 | DEMA(21)\n✅ 双重指数均线，比EMA更快速\n✅ 金叉/死叉信号比EMA更早\n✅ 减少均线滞后性的利器\n✅ 短线1-3天交易首选均线\n🔄 组合：DEMA+EMA21双线系统，DEMA+SAR快速止损',
  zigzag: '波段结构指标 | ZigZag(5%)\n✅ 自动标注波段高低点\n✅ 一目了然看清趋势结构\n✅ 忽略小波动，只看大趋势\n✅ 波段高低点是画趋势线的起点\n🔄 组合：ZigZag+Fibonacci回撤，ZigZag+MACD波段确认',
  avgAmp: '波动率指标 | 均幅(5/10/20)\n✅ 均幅=振幅的N日移动平均，衡量近期平均波动程度\n✅ 均幅上升=波动放大，适合波段操作\n✅ 均幅下降=波动收敛，可能即将变盘\n✅ 均幅5看短期波动，均幅20看中期波动\n🔄 组合：均幅+ATR双重波动确认，均幅+BOLL变盘预判',
  sats: '自适应趋势系统 | SATS(自感知趋势)\n✅ Supertrend升级版：带宽根据TQI动态调整\n✅ 红线=持股看多，绿线=观望看空(A股红涨绿跌)\n✅ TQI趋势质量指数(0~1)：高=强趋势窄通道，低=弱趋势宽通道\n✅ 非对称带宽：趋势方向收紧，反方向放宽(棘轮效应)\n✅ Character-Flip：TQI急剧下降时提前翻转，不等价格突破\n✅ 效率加权ATR：趋势行情ATR全重，震荡行情折半\n✅ 上/下轨线可视：主动侧收紧=趋势确认，被动侧放宽=保护利润\n🔄 组合：SATS+MACD趋势确认，SATS+ATR动态止损',
  alligator: '趋势+震荡判断 | 鳄鱼线(13,8,5)\n✅ 三线(颚/齿/唇)纠缠=鳄鱼沉睡，等待突破\n✅ 三线发散=鳄鱼张嘴，趋势启动\n✅ 唇(蓝)最灵敏 → 齿(红) → 颚(绿)最慢\n✅ 唇在齿上方+齿在颚上方=多头排列，反之空头\n⚠️ 纠缠期别操作，等张嘴再顺势入场\n🔄 组合：Alligator+AO确认动量，Alligator+Fractal精确入场',
  ao: '动量震荡器 | AO(5,34)\n✅ 零轴上翻红=多头动量增强，零轴下翻绿=空头动量增强\n✅ 碟形信号：零轴上方连续缩小再放大=买入\n✅ 双峰信号：零轴下方第二峰高于第一峰=买入\n✅ 零轴穿越：上穿=买入，下穿=卖出(最基础信号)\n🔄 组合：AO+Alligator经典BW组合，AO+MACD双重动量确认',
  hullMA: '低滞后均线 | Hull MA(9)\n✅ 比EMA/DEMA更灵敏且更平滑，极致减少滞后\n✅ 价格在Hull上方=多头，下方=空头\n✅ 转向点即为交易信号，比任何传统均线都快\n✅ 短线1-5天交易首选均线\n🔄 组合：HullMA+Supertrend趋势确认，HullMA+SAR快速止损',
  ad: '量价累计指标 | Accumulation/Distribution\n✅ A/D上升=资金积累(买方主导)\n✅ A/D下降=资金派发(卖方主导)\n✅ 比OBV更精确：考虑收盘在高低区间的位置\n✅ 收盘接近最高=A/D大幅上升，接近最低=大幅下降\n🔄 组合：A/D+MACD确认趋势，A/D+CMF资金流双重确认',
  trix: '三重平滑动量 | TRIX(15)\n✅ 三重EMA平滑，过滤99%噪声，信号极少但极准\n✅ TRIX上穿零轴=买入，下穿零轴=卖出\n✅ 信号线金叉/死叉比MACD更可靠\n✅ 趋势行情中TRIX方向=趋势方向\n🔄 组合：TRIX+MACD双重确认，TRIX+ADX过滤震荡',
  roc: '变动率 | ROC(12)\n✅ 最纯粹的动量指标=当前价/N日前价-1\n✅ ROC>0=上涨动量，<0=下跌动量\n✅ ROC创新高而价未创新高=动量衰竭\n✅ 零轴穿越=最简洁的买卖信号\n🔄 组合：ROC+MACD动量确认，ROC+RSI超买超卖',
  fractal: '波段分形 | Fractals(2)\n✅ 自动标注波段顶(↑)和底(↓)\n✅ Bill Williams三剑客之一，与Alligator配合最佳\n✅ 顶分形=卖出信号，底分形=买入信号\n✅ 分形突破=趋势确认(上破顶分形做多)\n🔄 组合：Fractals+Alligator精确入场，Fractals+AO动量确认',
  chop: '碎形指数 | Choppiness Index(14)\n✅ 判断趋势vs震荡：>61.8震荡，<38.2趋势\n✅ 与ADX互补：ADX=趋势强不强，CHOP=该不该做趋势\n✅ CHOP高位=别追涨杀跌，该用震荡策略\n✅ CHOP低位=顺势操作，该用趋势策略\n🔄 组合：CHOP+ADX双重确认，CHOP+Supertrend策略切换',
  elderRay: '牛熊力量 | Elder Ray(13)\n✅ Bull Power=最高价-EMA，衡量多头推力\n✅ Bear Power=最低价-EMA，衡量空头压力\n✅ Bull>0且上升=多头强势，<0=多头疲软\n✅ Bear<0且收窄=空头减弱，>0=空头极弱(强买)\n⚠️ Elder三重过滤法：用EMA定方向+Fractal定入场\n🔄 组合：ElderRay+EMA三重过滤，ElderRay+MACD背离确认',
  chaikinOsc: '蔡金震荡器 | Chaikin Oscillator(3,10)\n✅ A/D线的动量版(类似MACD对EMA的关系)\n✅ 零轴上方=资金流入加速，下方=流出加速\n✅ 背离价格=趋势反转信号\n✅ 比A/D线更敏感，比MFI更精确\n🔄 组合：ChaikinOsc+A/D方向+拐点，ChaikinOsc+MACD双重确认',
  vwapBands: 'VWAP通道 | VWAP Bands(20,2)\n✅ VWAP+成交量加权标准差=日内交易通道\n✅ 价格在上轨附近=过度买入，下轨附近=过度卖出\n✅ 中轨即VWAP=机构锚定价\n✅ 通道宽度=当前波动率，收窄=变盘\n🔄 组合：VWAPBands+BOLL双通道，VWAPBands+Pivot日内交易系统',
  massIndex: '反转凸起 | Mass Index(9,9,25)\n✅ 专门捕捉趋势反转信号\n✅ Mass>27=反转凸起，意味着趋势可能反转\n✅ Mass回落至26.5以下=确认信号，可以反向操作\n✅ 不指示方向，只提示"有大波动要来"\n🔄 组合：MassIndex+SAR方向判断，MassIndex+BOLL收窄确认',
  ulcerIndex: '溃疡指数 | Ulcer Index(14)\n✅ 衡量回撤深度和持续时间=持有痛苦指数\n✅ UI越高=近期回撤越大，持有越不安\n✅ UI从高位回落=最坏时期已过\n✅ 仓位管理神器：UI高时减仓，UI低时加仓\n🔄 组合：UI+ATR风险组合，UI+MA长期持有策略',
  coppock: '底部探测 | Coppock Curve(10,14,11)\n✅ 专门判断长期底部\n✅ 零轴下上穿=历史大底信号\n✅ 月线级别最有效，A股熊转牛强力信号\n✅ 不适合短线，适合判断大周期拐点\n🔄 组合：Coppock+CMO动量确认，Coppock+Pivot支撑位',
  tema: '三重指数均线 | TEMA(21)\n✅ EMA→DEMA→TEMA：滞后性递减\n✅ 比DEMA更灵敏，是终极低滞后均线\n✅ 价格在TEMA上方=多头，下方=空头\n✅ 适合需要快速响应的交易策略\n🔄 组合：TEMA+DEMA双均线，TEMA+MACD过滤假信号',
  smi: '随机动量 | SMI(14,3,3)\n✅ StochRSI的改良版：信号更平滑，噪声更少\n✅ 范围-100~+100，0轴即多空分界\n✅ +40以上超买，-40以下超卖\n✅ SMI上穿Signal=买入，下穿=卖出\n🔄 组合：SMI+StochRSI双重确认，SMI+MACD趋势过滤',
  smc: '聪明钱概念 | Smart Money Concepts\n🔴红大点=摆动高点(50期) 🟢绿大点=摆动低点(50期)\n🔴浅红小点=内部高点(5期) 🟢浅绿小点=内部低点(5期)\n🔵蓝色圆点=BOS 结构突破，趋势延续信号\n🟡黄色圆点=CHoCH 特征转变，趋势反转信号\n🟣靛蓝大点=SwBOS 大级别结构突破\n🟡金色大点=SwCHoCH 大级别特征转变\n🔴红点=FVG/OB看涨 🟢绿点=FVG/OB看跌\n🔄 组合：SMC+MACD确认结构突破，SMC+VWAP机构成本追踪',
  signalRatio: '综合信号比 | Signal Ratio\n🔴红线=看多%  🟢绿线=看空%  🟡黄线=净信号%(看多-看空)\n✅ 汇总38个技术指标信号，逐根K线评估\n✅ 净信号>0=多数看多，<0=多数看空\n✅ 净信号绝对值越大=多空共识越强\n✅ 净信号在零轴附近=多空分歧大，谨慎操作\n🔄 组合：SignalRatio+Supertrend趋势确认，SignalRatio+MACD拐点',
}
