// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {strategy} from '../models';

export function AbortChatWithAgent():Promise<void>;

export function AbortSummaryStockNews():Promise<void>;

export function ChatWithAgent(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:number,arg6:boolean,arg7:string):Promise<void>;

export function GetAllStrategies():Promise<Array<strategy.Strategy>>;

export function NewChatStream(arg1:string,arg2:string,arg3:string,arg4:number,arg5:any,arg6:boolean,arg7:boolean,arg8:string,arg9:string):Promise<void>;

export function NewCommodityAnalysisStream(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SetStockAICron(arg1:string,arg2:string):Promise<void>;

export function SummaryStockNews(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;
