// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortChatWithAgent() {
  return window['go']['handler']['AgentHandler']['AbortChatWithAgent']();
}

export function AbortSummaryStockNews() {
  return window['go']['handler']['AgentHandler']['AbortSummaryStockNews']();
}

export function ChatWithAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['handler']['AgentHandler']['ChatWithAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetAllStrategies() {
  return window['go']['handler']['AgentHandler']['GetAllStrategies']();
}

export function NewChatStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['handler']['AgentHandler']['NewChatStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function NewCommodityAnalysisStream(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['AgentHandler']['NewCommodityAnalysisStream'](arg1, arg2, arg3, arg4);
}

export function ReflectOnAnalysis(arg1, arg2, arg3) {
  return window['go']['handler']['AgentHandler']['ReflectOnAnalysis'](arg1, arg2, arg3);
}

export function SetStockAICron(arg1, arg2) {
  return window['go']['handler']['AgentHandler']['SetStockAICron'](arg1, arg2);
}

export function SummaryStockNews(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['handler']['AgentHandler']['SummaryStockNews'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
