// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIConfiguredStockPick(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['AIConfiguredStockPick'](arg1, arg2);
}

export function AddPrompt(arg1) {
  return window['go']['handler']['AnalysisHandler']['AddPrompt'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['handler']['AnalysisHandler']['AddPromptTemplate'](arg1);
}

export function AnalyzeSentiment(arg1) {
  return window['go']['handler']['AnalysisHandler']['AnalyzeSentiment'](arg1);
}

export function AnalyzeSentimentWithFreqWeight(arg1) {
  return window['go']['handler']['AnalysisHandler']['AnalyzeSentimentWithFreqWeight'](arg1);
}

export function BatchDeleteAIResponseResult(arg1) {
  return window['go']['handler']['AnalysisHandler']['BatchDeleteAIResponseResult'](arg1);
}

export function DelPrompt(arg1) {
  return window['go']['handler']['AnalysisHandler']['DelPrompt'](arg1);
}

export function DeleteAIResponseResult(arg1) {
  return window['go']['handler']['AnalysisHandler']['DeleteAIResponseResult'](arg1);
}

export function DeleteAiRecommendStocks(arg1) {
  return window['go']['handler']['AnalysisHandler']['DeleteAiRecommendStocks'](arg1);
}

export function DeleteCustomStrategy(arg1) {
  return window['go']['handler']['AnalysisHandler']['DeleteCustomStrategy'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['handler']['AnalysisHandler']['DeletePromptTemplate'](arg1);
}

export function GetAIResponseResult(arg1) {
  return window['go']['handler']['AnalysisHandler']['GetAIResponseResult'](arg1);
}

export function GetAIResponseResultList(arg1) {
  return window['go']['handler']['AnalysisHandler']['GetAIResponseResultList'](arg1);
}

export function GetAiRecommendStats() {
  return window['go']['handler']['AnalysisHandler']['GetAiRecommendStats']();
}

export function GetAiRecommendStocksList(arg1) {
  return window['go']['handler']['AnalysisHandler']['GetAiRecommendStocksList'](arg1);
}

export function GetAllCustomStrategies() {
  return window['go']['handler']['AnalysisHandler']['GetAllCustomStrategies']();
}

export function GetAllStocks(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['AnalysisHandler']['GetAllStocks'](arg1, arg2, arg3, arg4);
}

export function GetCustomStrategyList(arg1) {
  return window['go']['handler']['AnalysisHandler']['GetCustomStrategyList'](arg1);
}

export function GetHotStrategy() {
  return window['go']['handler']['AnalysisHandler']['GetHotStrategy']();
}

export function GetMultiAgentPrompts() {
  return window['go']['handler']['AnalysisHandler']['GetMultiAgentPrompts']();
}

export function GetPromptTemplateList(arg1) {
  return window['go']['handler']['AnalysisHandler']['GetPromptTemplateList'](arg1);
}

export function GetPromptTemplates(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['GetPromptTemplates'](arg1, arg2);
}

export function SaveAIResponseResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handler']['AnalysisHandler']['SaveAIResponseResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAsMarkdown(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['SaveAsMarkdown'](arg1, arg2);
}

export function SaveCustomStrategy(arg1) {
  return window['go']['handler']['AnalysisHandler']['SaveCustomStrategy'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['SaveImage'](arg1, arg2);
}

export function SaveWordFile(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['SaveWordFile'](arg1, arg2);
}

export function SearchStock(arg1) {
  return window['go']['handler']['AnalysisHandler']['SearchStock'](arg1);
}

export function ShareAnalysis(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['ShareAnalysis'](arg1, arg2);
}

export function ShareText(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['ShareText'](arg1, arg2);
}

export function UpdateAiRecommendStocksAlert(arg1, arg2) {
  return window['go']['handler']['AnalysisHandler']['UpdateAiRecommendStocksAlert'](arg1, arg2);
}

export function UpdateMultiAgentPrompt(arg1, arg2, arg3) {
  return window['go']['handler']['AnalysisHandler']['UpdateMultiAgentPrompt'](arg1, arg2, arg3);
}

export function UpdatePromptTemplate(arg1) {
  return window['go']['handler']['AnalysisHandler']['UpdatePromptTemplate'](arg1);
}
