// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {data} from '../models';

export function AIConfiguredStockPick(arg1:string,arg2:number):Promise<Array<models.DailyPick>>;

export function AddPrompt(arg1:models.Prompt):Promise<string>;

export function AddPromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function AnalyzeSentiment(arg1:string):Promise<models.SentimentResult>;

export function AnalyzeSentimentWithFreqWeight(arg1:string):Promise<Record<string, any>>;

export function BatchDeleteAIResponseResult(arg1:Array<number>):Promise<string>;

export function DelPrompt(arg1:number):Promise<string>;

export function DeleteAIResponseResult(arg1:number):Promise<string>;

export function DeleteAiRecommendStocks(arg1:number):Promise<string>;

export function DeleteCustomStrategy(arg1:number):Promise<string>;

export function DeletePromptTemplate(arg1:number):Promise<string>;

export function GetAIResponseResult(arg1:string):Promise<models.AIResponseResult>;

export function GetAIResponseResultList(arg1:models.AIResponseResultQuery):Promise<models.AIResponseResultPageData>;

export function GetAiRecommendStats():Promise<data.AiRecommendStats>;

export function GetAiRecommendStocksList(arg1:models.AiRecommendStocksQuery):Promise<models.AiRecommendStocksPageData>;

export function GetAllCustomStrategies():Promise<any>;

export function GetAllStocks(arg1:number,arg2:number,arg3:string,arg4:models.TechnicalIndicators):Promise<models.AllStocksResp>;

export function GetCustomStrategyList(arg1:models.CustomStrategyQuery):Promise<models.CustomStrategyPageData>;

export function GetHotStrategy():Promise<Record<string, any>>;

export function GetMultiAgentPrompts():Promise<Array<models.PromptTemplate>>;

export function GetPromptTemplateList(arg1:models.PromptTemplateQuery):Promise<models.PromptTemplatePageData>;

export function GetPromptTemplates(arg1:string,arg2:string):Promise<any>;

export function SaveAIResponseResult(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SaveAsMarkdown(arg1:string,arg2:string):Promise<string>;

export function SaveCustomStrategy(arg1:models.CustomStrategy):Promise<string>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveWordFile(arg1:string,arg2:string):Promise<string>;

export function SearchStock(arg1:string):Promise<Record<string, any>>;

export function ShareAnalysis(arg1:string,arg2:string):Promise<string>;

export function ShareText(arg1:string,arg2:string):Promise<string>;

export function UpdateAiRecommendStocksAlert(arg1:number,arg2:boolean):Promise<string>;

export function UpdateMultiAgentPrompt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdatePromptTemplate(arg1:models.PromptTemplate):Promise<string>;
