// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommodityCorrelation(arg1, arg2) {
  return window['go']['handler']['CommodityHandler']['GetCommodityCorrelation'](arg1, arg2);
}

export function GetCommodityFundamentals(arg1) {
  return window['go']['handler']['CommodityHandler']['GetCommodityFundamentals'](arg1);
}

export function GetCommodityKLine(arg1, arg2, arg3) {
  return window['go']['handler']['CommodityHandler']['GetCommodityKLine'](arg1, arg2, arg3);
}

export function GetCommodityKLineIntl(arg1, arg2, arg3) {
  return window['go']['handler']['CommodityHandler']['GetCommodityKLineIntl'](arg1, arg2, arg3);
}

export function GetCommodityQuote(arg1) {
  return window['go']['handler']['CommodityHandler']['GetCommodityQuote'](arg1);
}

export function GetCommodityQuoteIntl(arg1) {
  return window['go']['handler']['CommodityHandler']['GetCommodityQuoteIntl'](arg1);
}

export function GetCommodityRegistry() {
  return window['go']['handler']['CommodityHandler']['GetCommodityRegistry']();
}

export function GetCommodityReport(arg1, arg2) {
  return window['go']['handler']['CommodityHandler']['GetCommodityReport'](arg1, arg2);
}

export function GetCommodityTechnicals(arg1, arg2) {
  return window['go']['handler']['CommodityHandler']['GetCommodityTechnicals'](arg1, arg2);
}

export function GetMacroIndicatorsEnhanced() {
  return window['go']['handler']['CommodityHandler']['GetMacroIndicatorsEnhanced']();
}

export function GetTradableCommodities() {
  return window['go']['handler']['CommodityHandler']['GetTradableCommodities']();
}
