// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datasource} from '../models';
import {models} from '../models';
import {data} from '../models';

export function GetCommodityCorrelation(arg1:string,arg2:string):Promise<string>;

export function GetCommodityFundamentals(arg1:string):Promise<string>;

export function GetCommodityKLine(arg1:string,arg2:string,arg3:number):Promise<Array<datasource.KLineBar>>;

export function GetCommodityKLineIntl(arg1:string,arg2:string,arg3:number):Promise<Array<datasource.KLineBar>>;

export function GetCommodityQuote(arg1:string):Promise<datasource.QuoteData>;

export function GetCommodityQuoteIntl(arg1:string):Promise<datasource.QuoteData>;

export function GetCommodityRegistry():Promise<Array<models.CommodityAsset>>;

export function GetCommodityReport(arg1:string,arg2:string):Promise<string>;

export function GetCommodityTechnicals(arg1:string,arg2:string):Promise<string>;

export function GetMacroIndicatorsEnhanced():Promise<data.MacroSnapshotEnhanced>;

export function GetTradableCommodities():Promise<Array<models.CommodityAsset>>;
