// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDailyPick(arg1) {
  return window['go']['handler']['DailyPickHandler']['DeleteDailyPick'](arg1);
}

export function GetDailyPickStats() {
  return window['go']['handler']['DailyPickHandler']['GetDailyPickStats']();
}

export function GetDailyPicks(arg1) {
  return window['go']['handler']['DailyPickHandler']['GetDailyPicks'](arg1);
}

export function GetDateRange() {
  return window['go']['handler']['DailyPickHandler']['GetDateRange']();
}

export function GetLLMRankingEnabled() {
  return window['go']['handler']['DailyPickHandler']['GetLLMRankingEnabled']();
}

export function GetLatestPicks(arg1) {
  return window['go']['handler']['DailyPickHandler']['GetLatestPicks'](arg1);
}

export function GetLatestUnreviewedPicks() {
  return window['go']['handler']['DailyPickHandler']['GetLatestUnreviewedPicks']();
}

export function GetReviewSummary(arg1) {
  return window['go']['handler']['DailyPickHandler']['GetReviewSummary'](arg1);
}

export function GetReviewTrend(arg1) {
  return window['go']['handler']['DailyPickHandler']['GetReviewTrend'](arg1);
}

export function ReviewAllUnreviewed() {
  return window['go']['handler']['DailyPickHandler']['ReviewAllUnreviewed']();
}

export function RunDailyPick(arg1, arg2) {
  return window['go']['handler']['DailyPickHandler']['RunDailyPick'](arg1, arg2);
}

export function RunDailyPickAsync(arg1, arg2) {
  return window['go']['handler']['DailyPickHandler']['RunDailyPickAsync'](arg1, arg2);
}

export function RunDailyReview(arg1, arg2) {
  return window['go']['handler']['DailyPickHandler']['RunDailyReview'](arg1, arg2);
}

export function SetLLMRankingEnabled(arg1) {
  return window['go']['handler']['DailyPickHandler']['SetLLMRankingEnabled'](arg1);
}

export function UpdateDailyPickRemarks(arg1, arg2) {
  return window['go']['handler']['DailyPickHandler']['UpdateDailyPickRemarks'](arg1, arg2);
}
