// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteDailyPick(arg1:number):Promise<void>;

export function GetDailyPickStats():Promise<models.DailyPickStats>;

export function GetDailyPicks(arg1:models.DailyPickQuery):Promise<models.DailyPickPageData>;

export function GetDateRange():Promise<string|string>;

export function GetLLMRankingEnabled():Promise<boolean>;

export function GetLatestPicks(arg1:number):Promise<Array<models.DailyPick>>;

export function GetLatestUnreviewedPicks():Promise<Array<models.DailyPick>>;

export function GetReviewSummary(arg1:string):Promise<Record<string, any>>;

export function GetReviewTrend(arg1:number):Promise<Array<Record<string, any>>>;

export function ReviewAllUnreviewed():Promise<number>;

export function RunDailyPick(arg1:string,arg2:number):Promise<Array<models.DailyPick>>;

export function RunDailyPickAsync(arg1:string,arg2:number):Promise<void>;

export function RunDailyReview(arg1:string,arg2:string):Promise<number>;

export function SetLLMRankingEnabled(arg1:boolean):Promise<string>;

export function UpdateDailyPickRemarks(arg1:number,arg2:string):Promise<void>;
