// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FollowFund(arg1) {
  return window['go']['handler']['FundHandler']['FollowFund'](arg1);
}

export function GetFollowedFund() {
  return window['go']['handler']['FundHandler']['GetFollowedFund']();
}

export function GetFollowedFundPaged(arg1, arg2, arg3) {
  return window['go']['handler']['FundHandler']['GetFollowedFundPaged'](arg1, arg2, arg3);
}

export function GetFundHistoryNetValue(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['FundHandler']['GetFundHistoryNetValue'](arg1, arg2, arg3, arg4);
}

export function GetFundKLine(arg1, arg2, arg3) {
  return window['go']['handler']['FundHandler']['GetFundKLine'](arg1, arg2, arg3);
}

export function GetFundRanking(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handler']['FundHandler']['GetFundRanking'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetFundTop10Holdings(arg1) {
  return window['go']['handler']['FundHandler']['GetFundTop10Holdings'](arg1);
}

export function GetfundList(arg1) {
  return window['go']['handler']['FundHandler']['GetfundList'](arg1);
}

export function SearchFundCodes(arg1) {
  return window['go']['handler']['FundHandler']['SearchFundCodes'](arg1);
}

export function UnFollowFund(arg1) {
  return window['go']['handler']['FundHandler']['UnFollowFund'](arg1);
}
