// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function FollowFund(arg1:string):Promise<string>;

export function GetFollowedFund():Promise<Array<data.FollowedFund>>;

export function GetFollowedFundPaged(arg1:number,arg2:number,arg3:string):Promise<data.FollowedFundPagedResult>;

export function GetFundHistoryNetValue(arg1:string,arg2:number,arg3:string,arg4:string):Promise<Array<data.FundHistoryNetValue>>;

export function GetFundKLine(arg1:string,arg2:string,arg3:number):Promise<data.KLineSourceResult>;

export function GetFundRanking(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<data.FundRankingResult>;

export function GetFundTop10Holdings(arg1:string):Promise<Array<data.FundHoldingStock>>;

export function GetfundList(arg1:string):Promise<Array<data.FundBasic>>;

export function SearchFundCodes(arg1:string):Promise<Array<data.FundSearchItem>>;

export function UnFollowFund(arg1:string):Promise<string>;
