// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHunting(arg1) {
  return window['go']['handler']['KhunterHandler']['GetHunting'](arg1);
}

export function GetKellySuggestions() {
  return window['go']['handler']['KhunterHandler']['GetKellySuggestions']();
}

export function GetRiskLevel() {
  return window['go']['handler']['KhunterHandler']['GetRiskLevel']();
}

export function GetScores(arg1) {
  return window['go']['handler']['KhunterHandler']['GetScores'](arg1);
}

export function GetSignals(arg1) {
  return window['go']['handler']['KhunterHandler']['GetSignals'](arg1);
}

export function RunBacktestAsync(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['KhunterHandler']['RunBacktestAsync'](arg1, arg2, arg3, arg4);
}

export function RunPipelineAsync(arg1) {
  return window['go']['handler']['KhunterHandler']['RunPipelineAsync'](arg1);
}
