// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetHunting(arg1:string):Promise<Array<models.KhunterHunting>>;

export function GetRiskLevel():Promise<models.KhunterRiskLevel>;

export function GetScores(arg1:string):Promise<Array<models.KhunterScore>>;

export function GetSignals(arg1:string):Promise<Array<models.KhunterSignal>>;

export function RunBacktestAsync(arg1:Array<string>,arg2:string,arg3:string,arg4:number):Promise<Record<string, any>>;

export function RunPipelineAsync(arg1:string):Promise<Record<string, any>>;
