// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClsCalendar():Promise<Array<any>>;

export function EMDictCode(arg1:string):Promise<Array<any>>;

export function FetchAndSaveMarketStatistic():Promise<void>;

export function GetAllBKCodes():Promise<Array<Record<string, string>>>;

export function GetAllConceptCodes():Promise<Array<Record<string, string>>>;

export function GetBKFundFlowList(arg1:string,arg2:number):Promise<Array<models.BKFundFlowPoint>>;

export function GetBKFundFlowListByDate(arg1:string,arg2:string):Promise<Array<models.BKFundFlowPoint>>;

export function GetBKFundFlowTopList(arg1:number):Promise<Array<models.BKFundFlow>>;

export function GetBKFundFlowTopListByDate(arg1:string,arg2:number):Promise<Array<models.BKFundFlow>>;

export function GetConceptFundFlowList(arg1:string,arg2:number):Promise<Array<models.ConceptFundFlowPoint>>;

export function GetConceptFundFlowListByDate(arg1:string,arg2:string):Promise<Array<models.ConceptFundFlowPoint>>;

export function GetConceptFundFlowTopList(arg1:number):Promise<Array<models.ConceptFundFlow>>;

export function GetConceptFundFlowTopListByDate(arg1:string,arg2:number):Promise<Array<models.ConceptFundFlow>>;

export function GetIndustryMoneyRankSina(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetIndustryRank(arg1:string,arg2:number):Promise<Array<any>>;

export function GetLatestTradingDay():Promise<string>;

export function GetMarketStatisticByDate(arg1:string):Promise<Array<models.MarketStatistic>>;

export function GetMoneyRankSina(arg1:string):Promise<Array<Record<string, any>>>;

export function GetRecentDaysMarketStatistic(arg1:number):Promise<Array<models.MarketStatistic>>;

export function GetStockMoneyTrendByDay(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetTodayMarketStatistic():Promise<Array<models.MarketStatistic>>;

export function GetUplimitHot(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GlobalStockIndexes():Promise<Record<string, any>>;

export function GlobalStockIndexesReadable():Promise<string>;

export function HotEvent(arg1:number):Promise<any>;

export function HotStock(arg1:string):Promise<any>;

export function HotTopic(arg1:number):Promise<Array<any>>;

export function IndustryResearchReport(arg1:string):Promise<Array<any>>;

export function InvestCalendarTimeLine(arg1:string):Promise<Array<any>>;

export function IsHKTradingTime():Promise<boolean>;

export function IsTradingDay(arg1:string):Promise<boolean>;

export function IsTradingTime():Promise<boolean>;

export function IsUSTradingTime():Promise<boolean>;

export function LongTigerRank(arg1:string):Promise<any>;

export function StockNotice(arg1:string):Promise<Array<any>>;

export function StockResearchReport(arg1:string):Promise<Array<any>>;
