// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClsCalendar() {
  return window['go']['handler']['MarketHandler']['ClsCalendar']();
}

export function EMDictCode(arg1) {
  return window['go']['handler']['MarketHandler']['EMDictCode'](arg1);
}

export function FetchAndSaveMarketStatistic() {
  return window['go']['handler']['MarketHandler']['FetchAndSaveMarketStatistic']();
}

export function GetAllBKCodes() {
  return window['go']['handler']['MarketHandler']['GetAllBKCodes']();
}

export function GetAllConceptCodes() {
  return window['go']['handler']['MarketHandler']['GetAllConceptCodes']();
}

export function GetBKFundFlowList(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetBKFundFlowList'](arg1, arg2);
}

export function GetBKFundFlowListByDate(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetBKFundFlowListByDate'](arg1, arg2);
}

export function GetBKFundFlowTopList(arg1) {
  return window['go']['handler']['MarketHandler']['GetBKFundFlowTopList'](arg1);
}

export function GetBKFundFlowTopListByDate(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetBKFundFlowTopListByDate'](arg1, arg2);
}

export function GetConceptFundFlowList(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetConceptFundFlowList'](arg1, arg2);
}

export function GetConceptFundFlowListByDate(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetConceptFundFlowListByDate'](arg1, arg2);
}

export function GetConceptFundFlowTopList(arg1) {
  return window['go']['handler']['MarketHandler']['GetConceptFundFlowTopList'](arg1);
}

export function GetConceptFundFlowTopListByDate(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetConceptFundFlowTopListByDate'](arg1, arg2);
}

export function GetIndustryMoneyRankSina(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetIndustryMoneyRankSina'](arg1, arg2);
}

export function GetIndustryRank(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetIndustryRank'](arg1, arg2);
}

export function GetLatestTradingDay() {
  return window['go']['handler']['MarketHandler']['GetLatestTradingDay']();
}

export function GetMarketStatisticByDate(arg1) {
  return window['go']['handler']['MarketHandler']['GetMarketStatisticByDate'](arg1);
}

export function GetMoneyRankSina(arg1) {
  return window['go']['handler']['MarketHandler']['GetMoneyRankSina'](arg1);
}

export function GetRecentDaysMarketStatistic(arg1) {
  return window['go']['handler']['MarketHandler']['GetRecentDaysMarketStatistic'](arg1);
}

export function GetStockMoneyTrendByDay(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetStockMoneyTrendByDay'](arg1, arg2);
}

export function GetTodayMarketStatistic() {
  return window['go']['handler']['MarketHandler']['GetTodayMarketStatistic']();
}

export function GetUplimitHot(arg1, arg2) {
  return window['go']['handler']['MarketHandler']['GetUplimitHot'](arg1, arg2);
}

export function GlobalStockIndexes() {
  return window['go']['handler']['MarketHandler']['GlobalStockIndexes']();
}

export function GlobalStockIndexesReadable() {
  return window['go']['handler']['MarketHandler']['GlobalStockIndexesReadable']();
}

export function HotEvent(arg1) {
  return window['go']['handler']['MarketHandler']['HotEvent'](arg1);
}

export function HotStock(arg1) {
  return window['go']['handler']['MarketHandler']['HotStock'](arg1);
}

export function HotTopic(arg1) {
  return window['go']['handler']['MarketHandler']['HotTopic'](arg1);
}

export function IndustryResearchReport(arg1) {
  return window['go']['handler']['MarketHandler']['IndustryResearchReport'](arg1);
}

export function InvestCalendarTimeLine(arg1) {
  return window['go']['handler']['MarketHandler']['InvestCalendarTimeLine'](arg1);
}

export function IsHKTradingTime() {
  return window['go']['handler']['MarketHandler']['IsHKTradingTime']();
}

export function IsTradingDay(arg1) {
  return window['go']['handler']['MarketHandler']['IsTradingDay'](arg1);
}

export function IsTradingTime() {
  return window['go']['handler']['MarketHandler']['IsTradingTime']();
}

export function IsUSTradingTime() {
  return window['go']['handler']['MarketHandler']['IsUSTradingTime']();
}

export function LongTigerRank(arg1) {
  return window['go']['handler']['MarketHandler']['LongTigerRank'](arg1);
}

export function StockNotice(arg1) {
  return window['go']['handler']['MarketHandler']['StockNotice'](arg1);
}

export function StockResearchReport(arg1) {
  return window['go']['handler']['MarketHandler']['StockResearchReport'](arg1);
}
