// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewsBySector(arg1, arg2) {
  return window['go']['handler']['NewsHandler']['GetNewsBySector'](arg1, arg2);
}

export function GetSectors() {
  return window['go']['handler']['NewsHandler']['GetSectors']();
}

export function GetStockRelatedNews(arg1, arg2) {
  return window['go']['handler']['NewsHandler']['GetStockRelatedNews'](arg1, arg2);
}

export function GetTelegraphList(arg1) {
  return window['go']['handler']['NewsHandler']['GetTelegraphList'](arg1);
}

export function ReFleshTelegraphList(arg1) {
  return window['go']['handler']['NewsHandler']['ReFleshTelegraphList'](arg1);
}
