// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetNewsBySector(arg1:string,arg2:number):Promise<data.SectorNewsResponse>;

export function GetSectors():Promise<Array<data.Sector>>;

export function GetStockRelatedNews(arg1:string,arg2:number):Promise<Array<data.SectorNewsItem>>;

export function GetTelegraphList(arg1:string):Promise<any>;

export function ReFleshTelegraphList(arg1:string):Promise<any>;
