// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendDingDingMessage(arg1, arg2) {
  return window['go']['handler']['NotificationHandler']['SendDingDingMessage'](arg1, arg2);
}

export function SendDingDingMessageByType(arg1, arg2, arg3) {
  return window['go']['handler']['NotificationHandler']['SendDingDingMessageByType'](arg1, arg2, arg3);
}

export function SendTestNotification(arg1) {
  return window['go']['handler']['NotificationHandler']['SendTestNotification'](arg1);
}
