// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendDingDingMessage(arg1:string,arg2:string):Promise<string>;

export function SendDingDingMessageByType(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SendTestNotification(arg1:string):Promise<string>;
