// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function AddGroup(arg1:data.Group):Promise<string>;

export function AddStockGroup(arg1:number,arg2:string):Promise<string>;

export function Follow(arg1:string):Promise<string>;

export function GetChipDistribution(arg1:string,arg2:number,arg3:number,arg4:string):Promise<data.ChipDistributionResult>;

export function GetFollowList(arg1:number):Promise<any>;

export function GetGroupList():Promise<Array<data.Group>>;

export function GetGroupStockList(arg1:number):Promise<Array<data.GroupStock>>;

export function GetStockCommonKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockEastMoneyKLine(arg1:string,arg2:string,arg3:string,arg4:number):Promise<any>;

export function GetStockEastMoneyKLinePage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<any>;

export function GetStockKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockKLinePageWithFallback(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<data.KLineSourceResult>;

export function GetStockKLineWithFallback(arg1:string,arg2:string,arg3:string,arg4:number):Promise<data.KLineSourceResult>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetStockMinutePriceLineData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetTdxCallAuction(arg1:string,arg2:number,arg3:number):Promise<any>;

export function GetTdxCompanyInfo(arg1:string):Promise<data.TdxCompanyInfoBundle>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function InitializeGroupSort():Promise<boolean>;

export function RemoveGroup(arg1:number):Promise<string>;

export function RemoveStockGroup(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetAlarmChangePercent(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SetCostPriceAndVolume(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetStockSort(arg1:number,arg2:string):Promise<void>;

export function SetTradingPrice(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;

export function UnFollow(arg1:string):Promise<string>;

export function UpdateGroupSort(arg1:number,arg2:number):Promise<boolean>;
