// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteStockChangeHistory(arg1) {
  return window['go']['handler']['StockChangeHandler']['DeleteStockChangeHistory'](arg1);
}

export function GetAllStockChangesWithPaging(arg1) {
  return window['go']['handler']['StockChangeHandler']['GetAllStockChangesWithPaging'](arg1);
}

export function GetChangeRank(arg1, arg2) {
  return window['go']['handler']['StockChangeHandler']['GetChangeRank'](arg1, arg2);
}

export function GetChangeTypeDailyStats(arg1) {
  return window['go']['handler']['StockChangeHandler']['GetChangeTypeDailyStats'](arg1);
}

export function GetDailyChangeStats(arg1) {
  return window['go']['handler']['StockChangeHandler']['GetDailyChangeStats'](arg1);
}

export function GetDailyDimensionStats(arg1, arg2, arg3) {
  return window['go']['handler']['StockChangeHandler']['GetDailyDimensionStats'](arg1, arg2, arg3);
}

export function GetStockChangeHistory(arg1) {
  return window['go']['handler']['StockChangeHandler']['GetStockChangeHistory'](arg1);
}

export function GetStockChanges(arg1, arg2, arg3) {
  return window['go']['handler']['StockChangeHandler']['GetStockChanges'](arg1, arg2, arg3);
}

export function GetTypeStatsByDate(arg1) {
  return window['go']['handler']['StockChangeHandler']['GetTypeStatsByDate'](arg1);
}

export function SaveStockChangesToHistory(arg1) {
  return window['go']['handler']['StockChangeHandler']['SaveStockChangesToHistory'](arg1);
}
