// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllStockInfo(arg1) {
  return window['go']['handler']['StockHandler']['AddAllStockInfo'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['handler']['StockHandler']['AddGroup'](arg1);
}

export function AddStockGroup(arg1, arg2) {
  return window['go']['handler']['StockHandler']['AddStockGroup'](arg1, arg2);
}

export function BatchDeleteAllStockInfo(arg1) {
  return window['go']['handler']['StockHandler']['BatchDeleteAllStockInfo'](arg1);
}

export function DeleteAllStockInfo(arg1) {
  return window['go']['handler']['StockHandler']['DeleteAllStockInfo'](arg1);
}

export function Follow(arg1) {
  return window['go']['handler']['StockHandler']['Follow'](arg1);
}

export function GetAllConcepts() {
  return window['go']['handler']['StockHandler']['GetAllConcepts']();
}

export function GetAllIndustries() {
  return window['go']['handler']['StockHandler']['GetAllIndustries']();
}

export function GetAllMarkets() {
  return window['go']['handler']['StockHandler']['GetAllMarkets']();
}

export function GetAllStockInfoById(arg1) {
  return window['go']['handler']['StockHandler']['GetAllStockInfoById'](arg1);
}

export function GetAllStockInfoList(arg1) {
  return window['go']['handler']['StockHandler']['GetAllStockInfoList'](arg1);
}

export function GetChipDistribution(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['StockHandler']['GetChipDistribution'](arg1, arg2, arg3, arg4);
}

export function GetFollowList(arg1) {
  return window['go']['handler']['StockHandler']['GetFollowList'](arg1);
}

export function GetGroupList() {
  return window['go']['handler']['StockHandler']['GetGroupList']();
}

export function GetGroupStockList(arg1) {
  return window['go']['handler']['StockHandler']['GetGroupStockList'](arg1);
}

export function GetStockCommonKLine(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['GetStockCommonKLine'](arg1, arg2, arg3);
}

export function GetStockEastMoneyKLine(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['StockHandler']['GetStockEastMoneyKLine'](arg1, arg2, arg3, arg4);
}

export function GetStockEastMoneyKLinePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handler']['StockHandler']['GetStockEastMoneyKLinePage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockKLine(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['GetStockKLine'](arg1, arg2, arg3);
}

export function GetStockKLinePageWithFallback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handler']['StockHandler']['GetStockKLinePageWithFallback'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockKLineWithFallback(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['StockHandler']['GetStockKLineWithFallback'](arg1, arg2, arg3, arg4);
}

export function GetStockList(arg1) {
  return window['go']['handler']['StockHandler']['GetStockList'](arg1);
}

export function GetStockMinutePriceLineData(arg1, arg2) {
  return window['go']['handler']['StockHandler']['GetStockMinutePriceLineData'](arg1, arg2);
}

export function GetStockRealTimePrice(arg1) {
  return window['go']['handler']['StockHandler']['GetStockRealTimePrice'](arg1);
}

export function GetTdxCallAuction(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['GetTdxCallAuction'](arg1, arg2, arg3);
}

export function GetTdxCompanyCategoryContent(arg1, arg2) {
  return window['go']['handler']['StockHandler']['GetTdxCompanyCategoryContent'](arg1, arg2);
}

export function GetTdxCompanyCategoryList(arg1) {
  return window['go']['handler']['StockHandler']['GetTdxCompanyCategoryList'](arg1);
}

export function GetTdxCompanyInfo(arg1) {
  return window['go']['handler']['StockHandler']['GetTdxCompanyInfo'](arg1);
}

export function GetTdxFinanceInfo(arg1) {
  return window['go']['handler']['StockHandler']['GetTdxFinanceInfo'](arg1);
}

export function GetTdxSymbolBelongBoard(arg1) {
  return window['go']['handler']['StockHandler']['GetTdxSymbolBelongBoard'](arg1);
}

export function GetTdxXDXRInfo(arg1) {
  return window['go']['handler']['StockHandler']['GetTdxXDXRInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['handler']['StockHandler']['Greet'](arg1);
}

export function InitializeGroupSort() {
  return window['go']['handler']['StockHandler']['InitializeGroupSort']();
}

export function RemoveGroup(arg1) {
  return window['go']['handler']['StockHandler']['RemoveGroup'](arg1);
}

export function RemoveStockGroup(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['RemoveStockGroup'](arg1, arg2, arg3);
}

export function SetAlarmChangePercent(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['SetAlarmChangePercent'](arg1, arg2, arg3);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['handler']['StockHandler']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function SetStockSort(arg1, arg2) {
  return window['go']['handler']['StockHandler']['SetStockSort'](arg1, arg2);
}

export function SetTradingPrice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handler']['StockHandler']['SetTradingPrice'](arg1, arg2, arg3, arg4, arg5);
}

export function UnFollow(arg1) {
  return window['go']['handler']['StockHandler']['UnFollow'](arg1);
}

export function UpdateGroupSort(arg1, arg2) {
  return window['go']['handler']['StockHandler']['UpdateGroupSort'](arg1, arg2);
}
