// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {models} from '../models';

export function DeleteStockChangeHistory(arg1:number):Promise<string>;

export function GetAllStockChangesWithPaging(arg1:number):Promise<data.StockChangesResponse>;

export function GetChangeRank(arg1:number,arg2:number):Promise<data.ChangeRankResult>;

export function GetChangeTypeDailyStats(arg1:number):Promise<Array<data.ChangeTypeDailyStats>>;

export function GetDailyChangeStats(arg1:number):Promise<Array<data.DailyChangeStats>>;

export function GetDailyDimensionStats(arg1:string,arg2:string,arg3:number):Promise<Array<data.DailyDimensionStats>>;

export function GetStockChangeHistory(arg1:models.StockChangeHistoryQuery):Promise<models.StockChangeHistoryPageData>;

export function GetStockChanges(arg1:Array<number>,arg2:number,arg3:number):Promise<data.StockChangesResponse>;

export function GetTypeStatsByDate(arg1:string):Promise<Array<data.TypeCountStats>>;

export function SaveStockChangesToHistory(arg1:Array<number>):Promise<string>;
