// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {handler} from '../models';
import {data} from '../models';
import {lo} from '../models';

export function AbortSummaryStockNews():Promise<void>;

export function AnalyzeSkillEffectiveness(arg1:number):Promise<string>;

export function CalculateNextRunTime(arg1:string):Promise<string>;

export function CalculateNextRunTimes(arg1:string,arg2:number):Promise<Array<string>>;

export function CheckDeviceBinding(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckSponsorCode(arg1:string):Promise<Record<string, any>>;

export function CheckUpdate(arg1:number):Promise<void>;

export function CreateCronTask(arg1:models.CronTask):Promise<string>;

export function CreateMCPServer(arg1:models.MCPServer):Promise<string>;

export function CreateSkill(arg1:models.Skill):Promise<string>;

export function DeleteCronTask(arg1:number):Promise<string>;

export function DeleteMCPServer(arg1:number):Promise<string>;

export function DeleteSkill(arg1:number):Promise<string>;

export function EnableCronTask(arg1:number,arg2:boolean):Promise<string>;

export function EnableMCPServer(arg1:number,arg2:boolean):Promise<string>;

export function EnableSkill(arg1:number,arg2:boolean):Promise<string>;

export function ExecuteCronTaskNow(arg1:number):Promise<string>;

export function ExportConfig():Promise<string>;

export function FetchAiModelInfo(arg1:string,arg2:string,arg3:string):Promise<handler.AiModelInfo>;

export function FetchAiModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GenerateSkillFromURL(arg1:string):Promise<models.Skill>;

export function GetAiAssistantSession(arg1:string):Promise<models.AiAssistantSessionResp>;

export function GetAiConfigs():Promise<Array<data.AIConfig>>;

export function GetAllMCPTools():Promise<Array<models.MCPServerTool>>;

export function GetAllSkills():Promise<Array<models.Skill>>;

export function GetConfig():Promise<data.SettingConfig>;

export function GetCronTaskByID(arg1:number):Promise<models.CronTask>;

export function GetCronTaskList(arg1:models.CronTaskQuery):Promise<models.CronTaskPageResp>;

export function GetCronTaskTypes():Promise<Array<lo.Tuple2_string_string_>>;

export function GetEffectiveSponsorVip():Promise<Record<string, any>>;

export function GetMCPServerByID(arg1:number):Promise<models.MCPServer>;

export function GetMCPServerList(arg1:models.MCPServerQuery):Promise<models.MCPServerPageResp>;

export function GetMCPToolsByServerID(arg1:number):Promise<Array<models.MCPServerTool>>;

export function GetMachineId():Promise<string>;

export function GetSkillByID(arg1:number):Promise<models.Skill>;

export function GetSkillList(arg1:models.SkillQuery):Promise<models.SkillPageResp>;

export function GetSponsorInfo():Promise<Record<string, any>>;

export function GetTimezone():Promise<Record<string, any>>;

export function GetUserManual():Promise<string>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function InitCronTasks():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveAiAssistantSession(arg1:string,arg2:Array<models.AiAssistantMessage>):Promise<void>;

export function SearchCronTasks(arg1:string):Promise<Array<models.CronTask>>;

export function TestMCPServer(arg1:number):Promise<string>;

export function UpdateConfig(arg1:data.SettingConfig):Promise<string>;

export function UpdateCronTask(arg1:models.CronTask):Promise<string>;

export function UpdateMCPServer(arg1:models.MCPServer):Promise<string>;

export function UpdateSkill(arg1:models.Skill):Promise<string>;

export function ValidateCronExpr(arg1:string):Promise<string>;
