// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSummaryStockNews() {
  return window['go']['handler']['SystemHandler']['AbortSummaryStockNews']();
}

export function AnalyzeSkillEffectiveness(arg1) {
  return window['go']['handler']['SystemHandler']['AnalyzeSkillEffectiveness'](arg1);
}

export function CalculateNextRunTime(arg1) {
  return window['go']['handler']['SystemHandler']['CalculateNextRunTime'](arg1);
}

export function CalculateNextRunTimes(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['CalculateNextRunTimes'](arg1, arg2);
}

export function CheckDeviceBinding(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['CheckDeviceBinding'](arg1, arg2);
}

export function CheckSponsorCode(arg1) {
  return window['go']['handler']['SystemHandler']['CheckSponsorCode'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['handler']['SystemHandler']['CheckUpdate'](arg1);
}

export function CreateCronTask(arg1) {
  return window['go']['handler']['SystemHandler']['CreateCronTask'](arg1);
}

export function CreateMCPServer(arg1) {
  return window['go']['handler']['SystemHandler']['CreateMCPServer'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['handler']['SystemHandler']['CreateSkill'](arg1);
}

export function DeleteCronTask(arg1) {
  return window['go']['handler']['SystemHandler']['DeleteCronTask'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['handler']['SystemHandler']['DeleteMCPServer'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['handler']['SystemHandler']['DeleteSkill'](arg1);
}

export function EnableCronTask(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['EnableCronTask'](arg1, arg2);
}

export function EnableMCPServer(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['EnableMCPServer'](arg1, arg2);
}

export function EnableSkill(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['EnableSkill'](arg1, arg2);
}

export function ExecuteCronTaskNow(arg1) {
  return window['go']['handler']['SystemHandler']['ExecuteCronTaskNow'](arg1);
}

export function ExportConfig() {
  return window['go']['handler']['SystemHandler']['ExportConfig']();
}

export function FetchAiModelInfo(arg1, arg2, arg3) {
  return window['go']['handler']['SystemHandler']['FetchAiModelInfo'](arg1, arg2, arg3);
}

export function FetchAiModels(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['FetchAiModels'](arg1, arg2);
}

export function GenerateSkillFromURL(arg1) {
  return window['go']['handler']['SystemHandler']['GenerateSkillFromURL'](arg1);
}

export function GetAiAssistantSession(arg1) {
  return window['go']['handler']['SystemHandler']['GetAiAssistantSession'](arg1);
}

export function GetAiConfigs() {
  return window['go']['handler']['SystemHandler']['GetAiConfigs']();
}

export function GetAllMCPTools() {
  return window['go']['handler']['SystemHandler']['GetAllMCPTools']();
}

export function GetAllSkills() {
  return window['go']['handler']['SystemHandler']['GetAllSkills']();
}

export function GetConfig() {
  return window['go']['handler']['SystemHandler']['GetConfig']();
}

export function GetCronTaskByID(arg1) {
  return window['go']['handler']['SystemHandler']['GetCronTaskByID'](arg1);
}

export function GetCronTaskList(arg1) {
  return window['go']['handler']['SystemHandler']['GetCronTaskList'](arg1);
}

export function GetCronTaskTypes() {
  return window['go']['handler']['SystemHandler']['GetCronTaskTypes']();
}

export function GetEffectiveSponsorVip() {
  return window['go']['handler']['SystemHandler']['GetEffectiveSponsorVip']();
}

export function GetMCPServerByID(arg1) {
  return window['go']['handler']['SystemHandler']['GetMCPServerByID'](arg1);
}

export function GetMCPServerList(arg1) {
  return window['go']['handler']['SystemHandler']['GetMCPServerList'](arg1);
}

export function GetMCPToolsByServerID(arg1) {
  return window['go']['handler']['SystemHandler']['GetMCPToolsByServerID'](arg1);
}

export function GetMachineId() {
  return window['go']['handler']['SystemHandler']['GetMachineId']();
}

export function GetSkillByID(arg1) {
  return window['go']['handler']['SystemHandler']['GetSkillByID'](arg1);
}

export function GetSkillList(arg1) {
  return window['go']['handler']['SystemHandler']['GetSkillList'](arg1);
}

export function GetSponsorInfo() {
  return window['go']['handler']['SystemHandler']['GetSponsorInfo']();
}

export function GetTimezone() {
  return window['go']['handler']['SystemHandler']['GetTimezone']();
}

export function GetUserManual() {
  return window['go']['handler']['SystemHandler']['GetUserManual']();
}

export function GetVersionInfo() {
  return window['go']['handler']['SystemHandler']['GetVersionInfo']();
}

export function InitCronTasks() {
  return window['go']['handler']['SystemHandler']['InitCronTasks']();
}

export function OpenURL(arg1) {
  return window['go']['handler']['SystemHandler']['OpenURL'](arg1);
}

export function SaveAiAssistantSession(arg1, arg2) {
  return window['go']['handler']['SystemHandler']['SaveAiAssistantSession'](arg1, arg2);
}

export function SearchCronTasks(arg1) {
  return window['go']['handler']['SystemHandler']['SearchCronTasks'](arg1);
}

export function TestMCPServer(arg1) {
  return window['go']['handler']['SystemHandler']['TestMCPServer'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['handler']['SystemHandler']['UpdateConfig'](arg1);
}

export function UpdateCronTask(arg1) {
  return window['go']['handler']['SystemHandler']['UpdateCronTask'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['handler']['SystemHandler']['UpdateMCPServer'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['handler']['SystemHandler']['UpdateSkill'](arg1);
}

export function ValidateCronExpr(arg1) {
  return window['go']['handler']['SystemHandler']['ValidateCronExpr'](arg1);
}

export function TrackEvent(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['SystemHandler']['TrackEvent'](arg1, arg2, arg3, arg4);
}
