// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSummarizeHoldings() {
  return window['go']['handler']['TradingRecordHandler']['AbortSummarizeHoldings']();
}

export function AddTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['AddTradingRecord'](arg1);
}

export function AiSuggestPriceLevels(arg1, arg2, arg3) {
  return window['go']['handler']['TradingRecordHandler']['AiSuggestPriceLevels'](arg1, arg2, arg3);
}

export function AnalyzeHoldingsDeep(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['AnalyzeHoldingsDeep'](arg1, arg2);
}

export function CheckFrequentTrading(arg1) {
  return window['go']['handler']['TradingRecordHandler']['CheckFrequentTrading'](arg1);
}

export function DeleteTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['DeleteTradingRecord'](arg1);
}

export function GenerateTradeAiComment(arg1, arg2, arg3) {
  return window['go']['handler']['TradingRecordHandler']['GenerateTradeAiComment'](arg1, arg2, arg3);
}

export function GetAiAdviceForStock(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['GetAiAdviceForStock'](arg1, arg2);
}

export function GetHoldingsDeepData() {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsDeepData']();
}

export function GetHoldingsDetail() {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsDetail']();
}

export function GetHoldingsSignals() {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsSignals']();
}

export function GetHoldingsSummaryDetail(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsSummaryDetail'](arg1);
}

export function GetHoldingsSummaryList(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsSummaryList'](arg1, arg2);
}

export function GetKronosStatus() {
  return window['go']['handler']['TradingRecordHandler']['GetKronosStatus']();
}

export function GetStockTechnicalIndicators(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetStockTechnicalIndicators'](arg1);
}

export function GetStockSignals(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetStockSignals'](arg1);
}

export function GetStocksSignals(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetStocksSignals'](arg1);
}

export function GetStockSignalsAsOf(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['GetStockSignalsAsOf'](arg1, arg2);
}

export function GetSignalRegistry() {
  return window['go']['handler']['TradingRecordHandler']['GetSignalRegistry']();
}

export function GetTradingRecordById(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordById'](arg1);
}

export function GetTradingRecordList(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordList'](arg1);
}

export function GetTradingRecordStatistics() {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordStatistics']();
}

export function PredictKLine(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['PredictKLine'](arg1, arg2);
}

export function BacktestKLine(arg1, arg2, arg3) {
  return window['go']['handler']['TradingRecordHandler']['BacktestKLine'](arg1, arg2, arg3);
}

export function RollingBacktestKLine(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['TradingRecordHandler']['RollingBacktestKLine'](arg1, arg2, arg3, arg4);
}

export function StartKronosService() {
  return window['go']['handler']['TradingRecordHandler']['StartKronosService']();
}

export function StopKronosService() {
  return window['go']['handler']['TradingRecordHandler']['StopKronosService']();
}

export function SummarizeHoldings(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['SummarizeHoldings'](arg1, arg2);
}

export function UpdateTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['UpdateTradingRecord'](arg1);
}
