// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['AddTradingRecord'](arg1);
}

export function CheckFrequentTrading(arg1) {
  return window['go']['handler']['TradingRecordHandler']['CheckFrequentTrading'](arg1);
}

export function DeleteTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['DeleteTradingRecord'](arg1);
}

export function GetTradingRecordById(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordById'](arg1);
}

export function GetTradingRecordList(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordList'](arg1);
}

export function GetTradingRecordStatistics() {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordStatistics']();
}

export function UpdateTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['UpdateTradingRecord'](arg1);
}
