// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {models} from '../models';

export function AbortSummarizeHoldings():Promise<void>;

export function AddTradingRecord(arg1:data.TradingRecord):Promise<number>;

export function AiSuggestPriceLevels(arg1:string,arg2:string,arg3:number):Promise<data.TradingAiAdvice>;

export function CheckFrequentTrading(arg1:string):Promise<Record<string, any>>;

export function DeleteTradingRecord(arg1:number):Promise<void>;

export function GenerateTradeAiComment(arg1:number,arg2:number,arg3:string):Promise<void>;

export function GetAiAdviceForStock(arg1:string,arg2:string):Promise<data.TradingAiAdvice>;

export function GetHoldingsDetail():Promise<Array<data.HoldingsPosition>>;

export function GetHoldingsSummaryDetail(arg1:number):Promise<models.HoldingsDailySummary>;

export function GetHoldingsSummaryList(arg1:number,arg2:number):Promise<data.HoldingsSummaryPageData>;

export function GetStockTechnicalIndicators(arg1:string):Promise<data.StockIndicatorsResult>;

export function GetTradingRecordById(arg1:number):Promise<data.TradingRecord>;

export function GetTradingRecordList(arg1:data.TradingRecordListQuery):Promise<data.TradingRecordPageData>;

export function GetTradingRecordStatistics():Promise<data.TradingRecordStatistics>;

export function SummarizeHoldings(arg1:number,arg2:string):Promise<void>;

export function UpdateTradingRecord(arg1:data.TradingRecord):Promise<void>;
