// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSummarizeHoldings() {
  return window['go']['handler']['TradingRecordHandler']['AbortSummarizeHoldings']();
}

export function AddTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['AddTradingRecord'](arg1);
}

export function CheckFrequentTrading(arg1) {
  return window['go']['handler']['TradingRecordHandler']['CheckFrequentTrading'](arg1);
}

export function DeleteTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['DeleteTradingRecord'](arg1);
}

export function GetHoldingsDetail() {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsDetail']();
}

export function GetHoldingsSummaryDetail(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsSummaryDetail'](arg1);
}

export function GetHoldingsSummaryList(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['GetHoldingsSummaryList'](arg1, arg2);
}

export function GetStockTechnicalIndicators(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetStockTechnicalIndicators'](arg1);
}

export function GetTradingRecordById(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordById'](arg1);
}

export function GetTradingRecordList(arg1) {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordList'](arg1);
}

export function GetTradingRecordStatistics() {
  return window['go']['handler']['TradingRecordHandler']['GetTradingRecordStatistics']();
}

export function SummarizeHoldings(arg1, arg2) {
  return window['go']['handler']['TradingRecordHandler']['SummarizeHoldings'](arg1, arg2);
}

export function UpdateTradingRecord(arg1) {
  return window['go']['handler']['TradingRecordHandler']['UpdateTradingRecord'](arg1);
}
