// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function AddTradingRecord(arg1:data.TradingRecord):Promise<number>;

export function CheckFrequentTrading(arg1:string):Promise<Record<string, any>>;

export function DeleteTradingRecord(arg1:number):Promise<void>;

export function GetTradingRecordById(arg1:number):Promise<data.TradingRecord>;

export function GetTradingRecordList(arg1:data.TradingRecordListQuery):Promise<data.TradingRecordPageData>;

export function GetTradingRecordStatistics():Promise<data.TradingRecordStatistics>;

export function UpdateTradingRecord(arg1:data.TradingRecord):Promise<void>;
