// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBacktestResults(arg1, arg2, arg3) {
  return window['go']['backtest']['Service']['GetBacktestResults'](arg1, arg2, arg3);
}

export function GetKLineCacheStats() {
  return window['go']['backtest']['Service']['GetKLineCacheStats']();
}

export function GetLastSeedImportOutput() {
  return window['go']['backtest']['Service']['GetLastSeedImportOutput']();
}

export function GetOptimizationPresets() {
  return window['go']['backtest']['Service']['GetOptimizationPresets']();
}

export function GetSeedImportStatus() {
  return window['go']['backtest']['Service']['GetSeedImportStatus']();
}

export function GetSyncProgress() {
  return window['go']['backtest']['Service']['GetSyncProgress']();
}

export function RunBatchBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['backtest']['Service']['RunBatchBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RunOptimization(arg1) {
  return window['go']['backtest']['Service']['RunOptimization'](arg1);
}

export function RunSeedImport(arg1, arg2, arg3, arg4) {
  return window['go']['backtest']['Service']['RunSeedImport'](arg1, arg2, arg3, arg4);
}

export function RunSingleBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backtest']['Service']['RunSingleBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartHistoricalSync(arg1) {
  return window['go']['backtest']['Service']['StartHistoricalSync'](arg1);
}
