// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backtest} from '../models';

export function GetBacktestResults(arg1:string,arg2:number,arg3:number):Promise<models.AiRecommendBacktestPageData>;

export function GetKLineCacheStats():Promise<Record<string, any>>;

export function GetLastSeedImportOutput():Promise<string>;

export function GetSeedImportStatus():Promise<Record<string, any>>;

export function GetSyncProgress():Promise<Array<backtest.syncTaskItem>>;

export function RunBatchBacktest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:number,arg7:number,arg8:number,arg9:number):Promise<backtest.BatchResult>;

export function RunSeedImport(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function RunSingleBacktest(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:boolean):Promise<backtest.Result>;

export function StartHistoricalSync(arg1:number):Promise<void>;
