// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';
import {backtest} from '../models';

export function GetBacktestResults(arg1:context.Context,arg2:string,arg3:number,arg4:number):Promise<models.AiRecommendBacktestPageData>;

export function GetKLineCacheStats(arg1:context.Context):Promise<Record<string, any>>;

export function GetLastSeedImportOutput(arg1:context.Context):Promise<string>;

export function GetSeedImportStatus(arg1:context.Context):Promise<Record<string, any>>;

export function GetSyncProgress(arg1:context.Context):Promise<Array<backtest.syncTaskItem>>;

export function RunBatchBacktest(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:number,arg8:number,arg9:number,arg10:number):Promise<backtest.BatchResult>;

export function RunSeedImport(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function RunSingleBacktest(arg1:context.Context,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:boolean):Promise<backtest.Result>;

export function StartHistoricalSync(arg1:context.Context,arg2:number):Promise<void>;
