// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBacktestResults(arg1, arg2, arg3, arg4) {
  return window['go']['backtest']['Service']['GetBacktestResults'](arg1, arg2, arg3, arg4);
}

export function GetKLineCacheStats(arg1) {
  return window['go']['backtest']['Service']['GetKLineCacheStats'](arg1);
}

export function GetLastSeedImportOutput(arg1) {
  return window['go']['backtest']['Service']['GetLastSeedImportOutput'](arg1);
}

export function GetSeedImportStatus(arg1) {
  return window['go']['backtest']['Service']['GetSeedImportStatus'](arg1);
}

export function GetSyncProgress(arg1) {
  return window['go']['backtest']['Service']['GetSyncProgress'](arg1);
}

export function RunBatchBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['backtest']['Service']['RunBatchBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function RunSeedImport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backtest']['Service']['RunSeedImport'](arg1, arg2, arg3, arg4, arg5);
}

export function RunSingleBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['backtest']['Service']['RunSingleBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartHistoricalSync(arg1, arg2) {
  return window['go']['backtest']['Service']['StartHistoricalSync'](arg1, arg2);
}
