// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {context} from '../models';

export function AddCronTask(arg1:data.FollowedStock):Promise<any>;

export function CheckStockBaseInfo(arg1:context.Context):Promise<void>;

export function GenerateSkillFromURL(arg1:string):Promise<string>;

export function HideToTray():Promise<void>;

export function InitCronTasks():Promise<void>;

export function NewsPush(arg1:any):Promise<void>;

export function QuitApp():Promise<void>;

export function RestartAsAdmin():Promise<void>;

export function ShowFromTray():Promise<void>;

export function UpdateConfig(arg1:data.SettingConfig):Promise<string>;
