// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronTask(arg1) {
  return window['go']['main']['App']['AddCronTask'](arg1);
}

export function CheckStockBaseInfo(arg1) {
  return window['go']['main']['App']['CheckStockBaseInfo'](arg1);
}

export function GenerateSkillFromURL(arg1) {
  return window['go']['main']['App']['GenerateSkillFromURL'](arg1);
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function InitCronTasks() {
  return window['go']['main']['App']['InitCronTasks']();
}

export function NewsPush(arg1) {
  return window['go']['main']['App']['NewsPush'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
